package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

object ChineseSimplifiedBookNames : BookNameLocalization {
    private val fullNames = mapOf(
        BibleBook.GEN to "创世记",
        BibleBook.EXOD to "出埃及记",
        BibleBook.LEV to "利未记",
        BibleBook.NUM to "民数记",
        BibleBook.DEUT to "申命记",
        BibleBook.JOSH to "约书亚记",
        BibleBook.JUDG to "士师记",
        BibleBook.RUTH to "路得记",
        BibleBook.SAM1 to "撒母耳记上",
        BibleBook.SAM2 to "撒母耳记下",
        BibleBook.KGS1 to "列王纪上",
        BibleBook.KGS2 to "列王纪下",
        BibleBook.CHR1 to "历代志上",
        BibleBook.CHR2 to "历代志下",
        BibleBook.EZRA to "以斯拉记",
        BibleBook.NEH to "尼希米记",
        BibleBook.ESTH to "以斯帖记",
        BibleBook.JOB to "约伯记",
        BibleBook.PS to "诗篇",
        BibleBook.PROV to "箴言",
        BibleBook.ECCL to "传道书",
        BibleBook.SONG to "雅歌",
        BibleBook.ISA to "以赛亚书",
        BibleBook.JER to "耶利米书",
        BibleBook.LAM to "耶利米哀歌",
        BibleBook.EZEK to "以西结书",
        BibleBook.DAN to "但以理书",
        BibleBook.HOS to "何西阿书",
        BibleBook.JOEL to "约珥书",
        BibleBook.AMOS to "阿摩司书",
        BibleBook.OBAD to "俄巴底亚书",
        BibleBook.JONAH to "约拿书",
        BibleBook.MIC to "弥迦书",
        BibleBook.NAH to "那鸿书",
        BibleBook.HAB to "哈巴谷书",
        BibleBook.ZEPH to "西番雅书",
        BibleBook.HAG to "哈该书",
        BibleBook.ZECH to "撒迦利亚书",
        BibleBook.MAL to "玛拉基书",
        BibleBook.MATT to "马太福音",
        BibleBook.MARK to "马可福音",
        BibleBook.LUKE to "路加福音",
        BibleBook.JOHN to "约翰福音",
        BibleBook.ACTS to "使徒行传",
        BibleBook.ROM to "罗马书",
        BibleBook.COR1 to "哥林多前书",
        BibleBook.COR2 to "哥林多后书",
        BibleBook.GAL to "加拉太书",
        BibleBook.EPH to "以弗所书",
        BibleBook.PHIL to "腓立比书",
        BibleBook.COL to "歌罗西书",
        BibleBook.THESS1 to "帖撒罗尼迦前书",
        BibleBook.THESS2 to "帖撒罗尼迦后书",
        BibleBook.TIM1 to "提摩太前书",
        BibleBook.TIM2 to "提摩太后书",
        BibleBook.TITUS to "提多书",
        BibleBook.PHLM to "腓利门书",
        BibleBook.HEB to "希伯来书",
        BibleBook.JAS to "雅各书",
        BibleBook.PET1 to "彼得前书",
        BibleBook.PET2 to "彼得后书",
        BibleBook.JOHN1 to "约翰一书",
        BibleBook.JOHN2 to "约翰二书",
        BibleBook.JOHN3 to "约翰三书",
        BibleBook.JUDE to "犹大书",
        BibleBook.REV to "启示录"
    )

    private val shortNames = mapOf(
        BibleBook.GEN to "创",
        BibleBook.EXOD to "出",
        BibleBook.LEV to "利",
        BibleBook.NUM to "民",
        BibleBook.DEUT to "申",
        BibleBook.JOSH to "书",
        BibleBook.JUDG to "士",
        BibleBook.RUTH to "得",
        BibleBook.SAM1 to "撒上",
        BibleBook.SAM2 to "撒下",
        BibleBook.KGS1 to "王上",
        BibleBook.KGS2 to "王下",
        BibleBook.CHR1 to "代上",
        BibleBook.CHR2 to "代下",
        BibleBook.EZRA to "拉",
        BibleBook.NEH to "尼",
        BibleBook.ESTH to "斯",
        BibleBook.JOB to "伯",
        BibleBook.PS to "诗",
        BibleBook.PROV to "箴",
        BibleBook.ECCL to "传",
        BibleBook.SONG to "歌",
        BibleBook.ISA to "赛",
        BibleBook.JER to "耶",
        BibleBook.LAM to "哀",
        BibleBook.EZEK to "结",
        BibleBook.DAN to "但",
        BibleBook.HOS to "何",
        BibleBook.JOEL to "珥",
        BibleBook.AMOS to "摩",
        BibleBook.OBAD to "俄",
        BibleBook.JONAH to "拿",
        BibleBook.MIC to "弥",
        BibleBook.NAH to "鸿",
        BibleBook.HAB to "哈",
        BibleBook.ZEPH to "番",
        BibleBook.HAG to "该",
        BibleBook.ZECH to "亚",
        BibleBook.MAL to "玛",
        BibleBook.MATT to "太",
        BibleBook.MARK to "可",
        BibleBook.LUKE to "路",
        BibleBook.JOHN to "约",
        BibleBook.ACTS to "徒",
        BibleBook.ROM to "罗",
        BibleBook.COR1 to "林前",
        BibleBook.COR2 to "林后",
        BibleBook.GAL to "加",
        BibleBook.EPH to "弗",
        BibleBook.PHIL to "腓",
        BibleBook.COL to "西",
        BibleBook.THESS1 to "帖前",
        BibleBook.THESS2 to "帖后",
        BibleBook.TIM1 to "提前",
        BibleBook.TIM2 to "提后",
        BibleBook.TITUS to "多",
        BibleBook.PHLM to "门",
        BibleBook.HEB to "来",
        BibleBook.JAS to "雅",
        BibleBook.PET1 to "彼前",
        BibleBook.PET2 to "彼后",
        BibleBook.JOHN1 to "约一",
        BibleBook.JOHN2 to "约二",
        BibleBook.JOHN3 to "约三",
        BibleBook.JUDE to "犹",
        BibleBook.REV to "启"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]
    override fun getShortName(book: BibleBook): String? = shortNames[book]
    override fun getAlternateName(book: BibleBook): String? = null
}
