package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

object DutchBookNames : BookNameLocalization {
    private val fullNames = mapOf(
        BibleBook.GEN to "Genesis",
        BibleBook.EXOD to "Exodus",
        BibleBook.LEV to "Leviticus",
        BibleBook.NUM to "Numeri",
        BibleBook.DEUT to "Deuteronomium",
        BibleBook.JOSH to "Jozua",
        BibleBook.JUDG to "Richteren",
        BibleBook.RUTH to "Ruth",
        BibleBook.SAM1 to "1 Samuël",
        BibleBook.SAM2 to "2 Samuël",
        BibleBook.KGS1 to "1 Koningen",
        BibleBook.KGS2 to "2 Koningen",
        BibleBook.CHR1 to "1 Kronieken",
        BibleBook.CHR2 to "2 Kronieken",
        BibleBook.EZRA to "Ezra",
        BibleBook.NEH to "Nehemia",
        BibleBook.ESTH to "Esther",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Psalmen",
        BibleBook.PROV to "Spreuken",
        BibleBook.ECCL to "Prediker",
        BibleBook.SONG to "Hooglied",
        BibleBook.ISA to "Jesaja",
        BibleBook.JER to "Jeremia",
        BibleBook.LAM to "Klaagliederen",
        BibleBook.EZEK to "Ezechiël",
        BibleBook.DAN to "Daniel",
        BibleBook.HOS to "Hosea",
        BibleBook.JOEL to "Joël",
        BibleBook.AMOS to "Amos",
        BibleBook.OBAD to "Obadja",
        BibleBook.JONAH to "Jona",
        BibleBook.MIC to "Micha",
        BibleBook.NAH to "Nahum",
        BibleBook.HAB to "Habakuk",
        BibleBook.ZEPH to "Zefanja",
        BibleBook.HAG to "Haggaï",
        BibleBook.ZECH to "Zacharia",
        BibleBook.MAL to "Maleachi",
        BibleBook.MATT to "Mattheüs",
        BibleBook.MARK to "Markus",
        BibleBook.LUKE to "Lukas",
        BibleBook.JOHN to "Johannes",
        BibleBook.ACTS to "Handelingen",
        BibleBook.ROM to "Romeinen",
        BibleBook.COR1 to "1 Korintiërs",
        BibleBook.COR2 to "2 Korintiërs",
        BibleBook.GAL to "Galaten",
        BibleBook.EPH to "Efeziërs",
        BibleBook.PHIL to "Filippenzen",
        BibleBook.COL to "Kolossenzen",
        BibleBook.THESS1 to "1 Thessalonicenzen",
        BibleBook.THESS2 to "2 Thessalonicenzen",
        BibleBook.TIM1 to "1 Timotheüs",
        BibleBook.TIM2 to "2 Timotheüs",
        BibleBook.TITUS to "Titus",
        BibleBook.PHLM to "Filemon",
        BibleBook.HEB to "Hebreeën",
        BibleBook.JAS to "Jakobus",
        BibleBook.PET1 to "1 Petrus",
        BibleBook.PET2 to "2 Petrus",
        BibleBook.JOHN1 to "1 Johannes",
        BibleBook.JOHN2 to "2 Johannes",
        BibleBook.JOHN3 to "3 Johannes",
        BibleBook.JUDE to "Judas",
        BibleBook.REV to "Openbaring van Johannes"
    )

    private val shortNames = mapOf(
        BibleBook.GEN to "Gen",
        BibleBook.EXOD to "Exo",
        BibleBook.LEV to "Lev",
        BibleBook.NUM to "Num",
        BibleBook.DEUT to "Deu",
        BibleBook.JOSH to "Joz",
        BibleBook.JUDG to "Richt",
        BibleBook.RUTH to "Rut",
        BibleBook.SAM1 to "1Sam",
        BibleBook.SAM2 to "2Sam",
        BibleBook.KGS1 to "1Kon",
        BibleBook.KGS2 to "2Kon",
        BibleBook.CHR1 to "1Kro",
        BibleBook.CHR2 to "2Kro",
        BibleBook.EZRA to "Ezr",
        BibleBook.NEH to "Neh",
        BibleBook.ESTH to "Est",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Psa",
        BibleBook.PROV to "Spr",
        BibleBook.ECCL to "Pre",
        BibleBook.SONG to "Hoog",
        BibleBook.ISA to "Jes",
        BibleBook.JER to "Jer",
        BibleBook.LAM to "Klaag",
        BibleBook.EZEK to "Eze",
        BibleBook.DAN to "Dan",
        BibleBook.HOS to "Hos",
        BibleBook.JOEL to "Joë",
        BibleBook.AMOS to "Amo",
        BibleBook.OBAD to "Obd",
        BibleBook.JONAH to "Jon",
        BibleBook.MIC to "Mic",
        BibleBook.NAH to "Nah",
        BibleBook.HAB to "Hab",
        BibleBook.ZEPH to "Zef",
        BibleBook.HAG to "Hag",
        BibleBook.ZECH to "Zach",
        BibleBook.MAL to "Mal",
        BibleBook.MATT to "Mat",
        BibleBook.MARK to "Mar",
        BibleBook.LUKE to "Luk",
        BibleBook.JOHN to "Joh",
        BibleBook.ACTS to "Hand",
        BibleBook.ROM to "Rom",
        BibleBook.COR1 to "1Kor",
        BibleBook.COR2 to "2Kor",
        BibleBook.GAL to "Gal",
        BibleBook.EPH to "Ef",
        BibleBook.PHIL to "Fil",
        BibleBook.COL to "Kol",
        BibleBook.THESS1 to "1Tes",
        BibleBook.THESS2 to "2Tes",
        BibleBook.TIM1 to "1Tim",
        BibleBook.TIM2 to "2Tim",
        BibleBook.TITUS to "Tit",
        BibleBook.PHLM to "File",
        BibleBook.HEB to "Heb",
        BibleBook.JAS to "Jak",
        BibleBook.PET1 to "1Pet",
        BibleBook.PET2 to "2Pet",
        BibleBook.JOHN1 to "1Joh",
        BibleBook.JOHN2 to "2Joh",
        BibleBook.JOHN3 to "3Joh",
        BibleBook.JUDE to "Jud",
        BibleBook.REV to "Openb"
    )

    private val alternateNames = mapOf(
        BibleBook.DEUT to "dt",
        BibleBook.JUDG to "jdg,jud",
        BibleBook.RUTH to "rth",
        BibleBook.SAM1 to "isamuel",
        BibleBook.SAM2 to "iisamuel",
        BibleBook.KGS1 to "1kg,ikings,ikgs",
        BibleBook.KGS2 to "2kgs,iikings,iikgs",
        BibleBook.CHR1 to "1 Kronieken",
        BibleBook.CHR2 to "iichronicles",
        BibleBook.PS to "pss,psm",
        BibleBook.ECCL to "qohelet",
        BibleBook.SONG to "ss,songofsongs,sos,canticleofcanticles,canticle,can,coc,sng",
        BibleBook.ISA to "is",
        BibleBook.EZEK to "Ezk",
        BibleBook.JOEL to "Jol",
        BibleBook.JONAH to "jnh",
        BibleBook.NAH to "Nam",
        BibleBook.MATT to "mt",
        BibleBook.MARK to "mk,mrk",
        BibleBook.LUKE to "lk",
        BibleBook.JOHN to "jn,jhn",
        BibleBook.COR1 to "icorinthians",
        BibleBook.COR2 to "iicorinthians",
        BibleBook.PHIL to "php",
        BibleBook.COL to "co",
        BibleBook.THESS1 to "ith",
        BibleBook.THESS2 to "iith",
        BibleBook.TIM1 to "1tm,iti,itm",
        BibleBook.TIM2 to "2tm,iiti,iitm",
        BibleBook.PHLM to "phm,phlm",
        BibleBook.JAS to "jas",
        BibleBook.PET1 to "1ptr,ip",
        BibleBook.PET2 to "2pt,iip",
        BibleBook.JOHN1 to "1jn,1jh,ijo,ijn,ijh",
        BibleBook.JOHN2 to "2jn,2jh,iijo,iijn,iijh",
        BibleBook.JOHN3 to "3jn,3jh,iiijo,iiijn,iiijh",
        BibleBook.REV to "rv,apocalypse",
        BibleBook.SIR to "Ecclesiasticus",
        BibleBook.EP_JER to "letterofjeremiah,letterjeremiah,epistlejeremiah,epjeremiah",
        BibleBook.PR_AZAR to "prayerazariah,prayazariah,songofthreechildren,songthreechildren,songof3children,song3children,S3Y",
        BibleBook.BEL to "beldragon,belanddragon",
        BibleBook.MACC1 to "imaccabees",
        BibleBook.MACC2 to "iimacabees",
        BibleBook.MACC3 to "iiimacabees",
        BibleBook.MACC4 to "ivmac",
        BibleBook.PR_MAN to "prayermanasseh,praymanasseh,prmanasseh",
        BibleBook.ESD1 to "iesdras",
        BibleBook.ESD2 to "iiesdras",
        BibleBook.PSS151 to "pss151,psm151",
        BibleBook.PSALM_SOL to "psssolomon,psmsolomon",
        BibleBook.EP_LAO to "eplaodiceans",
        BibleBook.ESD3 to "iiiesdras",
        BibleBook.ESD4 to "ivesdras",
        BibleBook.ESD5 to "vesdras",
        BibleBook.EN1 to "ienoch",
        BibleBook.CLEM1 to "iiclement",
        BibleBook.CLEM2 to "iiclement"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]
    override fun getShortName(book: BibleBook): String? = shortNames[book]
    override fun getAlternateName(book: BibleBook): String? = alternateNames[book]
}
