package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

/**
 * English localization for Bible book names
 */
object EnglishBookNames : BookNameLocalization {

    private val fullNames = mapOf(
        // Introductions
        BibleBook.INTRO_BIBLE to "Introduction to the Bible",
        BibleBook.INTRO_OT to "Introduction to the Old Testament",
        BibleBook.INTRO_NT to "Introduction to the New Testament",

        // Old Testament
        BibleBook.GEN to "Genesis",
        BibleBook.EXOD to "Exodus",
        BibleBook.LEV to "Leviticus",
        BibleBook.NUM to "Numbers",
        BibleBook.DEUT to "Deuteronomy",
        BibleBook.JOSH to "Joshua",
        BibleBook.JUDG to "Judges",
        BibleBook.RUTH to "Ruth",
        BibleBook.SAM1 to "1 Samuel",
        BibleBook.SAM2 to "2 Samuel",
        BibleBook.KGS1 to "1 Kings",
        BibleBook.KGS2 to "2 Kings",
        BibleBook.CHR1 to "1 Chronicles",
        BibleBook.CHR2 to "2 Chronicles",
        BibleBook.EZRA to "Ezra",
        BibleBook.NEH to "Nehemiah",
        BibleBook.ESTH to "Esther",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Psalms",
        BibleBook.PROV to "Proverbs",
        BibleBook.ECCL to "Ecclesiastes",
        BibleBook.SONG to "Song of Solomon",
        BibleBook.ISA to "Isaiah",
        BibleBook.JER to "Jeremiah",
        BibleBook.LAM to "Lamentations",
        BibleBook.EZEK to "Ezekiel",
        BibleBook.DAN to "Daniel",
        BibleBook.HOS to "Hosea",
        BibleBook.JOEL to "Joel",
        BibleBook.AMOS to "Amos",
        BibleBook.OBAD to "Obadiah",
        BibleBook.JONAH to "Jonah",
        BibleBook.MIC to "Micah",
        BibleBook.NAH to "Nahum",
        BibleBook.HAB to "Habakkuk",
        BibleBook.ZEPH to "Zephaniah",
        BibleBook.HAG to "Haggai",
        BibleBook.ZECH to "Zechariah",
        BibleBook.MAL to "Malachi",

        // New Testament
        BibleBook.MATT to "Matthew",
        BibleBook.MARK to "Mark",
        BibleBook.LUKE to "Luke",
        BibleBook.JOHN to "John",
        BibleBook.ACTS to "Acts",
        BibleBook.ROM to "Romans",
        BibleBook.COR1 to "1 Corinthians",
        BibleBook.COR2 to "2 Corinthians",
        BibleBook.GAL to "Galatians",
        BibleBook.EPH to "Ephesians",
        BibleBook.PHIL to "Philippians",
        BibleBook.COL to "Colossians",
        BibleBook.THESS1 to "1 Thessalonians",
        BibleBook.THESS2 to "2 Thessalonians",
        BibleBook.TIM1 to "1 Timothy",
        BibleBook.TIM2 to "2 Timothy",
        BibleBook.TITUS to "Titus",
        BibleBook.PHLM to "Philemon",
        BibleBook.HEB to "Hebrews",
        BibleBook.JAS to "James",
        BibleBook.PET1 to "1 Peter",
        BibleBook.PET2 to "2 Peter",
        BibleBook.JOHN1 to "1 John",
        BibleBook.JOHN2 to "2 John",
        BibleBook.JOHN3 to "3 John",
        BibleBook.JUDE to "Jude",
        BibleBook.REV to "Revelation",

        // Apocrypha
        BibleBook.TOB to "Tobit",
        BibleBook.JDT to "Judith",
        BibleBook.ADD_ESTH to "Additions to Esther",
        BibleBook.WIS to "Wisdom",
        BibleBook.SIR to "Sirach",
        BibleBook.BAR to "Baruch",
        BibleBook.EP_JER to "Letter of Jeremiah",
        BibleBook.PR_AZAR to "Prayer of Azariah",
        BibleBook.SUS to "Susanna",
        BibleBook.BEL to "Bel and the Dragon",
        BibleBook.MACC1 to "1 Maccabees",
        BibleBook.MACC2 to "2 Maccabees",
        BibleBook.MACC3 to "3 Maccabees",
        BibleBook.MACC4 to "4 Maccabees",
        BibleBook.PR_MAN to "Prayer of Manasseh",
        BibleBook.ESD1 to "1 Esdras",
        BibleBook.ESD2 to "2 Esdras",
        BibleBook.PSS151 to "Psalm 151"
    )

    private val shortNames = mapOf(
        // Introductions
        BibleBook.INTRO_BIBLE to "Intro",
        BibleBook.INTRO_OT to "Intro OT",
        BibleBook.INTRO_NT to "Intro NT",

        // Old Testament
        BibleBook.GEN to "Gen",
        BibleBook.EXOD to "Exod",
        BibleBook.LEV to "Lev",
        BibleBook.NUM to "Num",
        BibleBook.DEUT to "Deut",
        BibleBook.JOSH to "Josh",
        BibleBook.JUDG to "Judg",
        BibleBook.RUTH to "Ruth",
        BibleBook.SAM1 to "1Sam",
        BibleBook.SAM2 to "2Sam",
        BibleBook.KGS1 to "1Kgs",
        BibleBook.KGS2 to "2Kgs",
        BibleBook.CHR1 to "1Chr",
        BibleBook.CHR2 to "2Chr",
        BibleBook.EZRA to "Ezra",
        BibleBook.NEH to "Neh",
        BibleBook.ESTH to "Esth",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Ps",
        BibleBook.PROV to "Prov",
        BibleBook.ECCL to "Eccl",
        BibleBook.SONG to "Song",
        BibleBook.ISA to "Isa",
        BibleBook.JER to "Jer",
        BibleBook.LAM to "Lam",
        BibleBook.EZEK to "Ezek",
        BibleBook.DAN to "Dan",
        BibleBook.HOS to "Hos",
        BibleBook.JOEL to "Joel",
        BibleBook.AMOS to "Amos",
        BibleBook.OBAD to "Obad",
        BibleBook.JONAH to "Jonah",
        BibleBook.MIC to "Mic",
        BibleBook.NAH to "Nah",
        BibleBook.HAB to "Hab",
        BibleBook.ZEPH to "Zeph",
        BibleBook.HAG to "Hag",
        BibleBook.ZECH to "Zech",
        BibleBook.MAL to "Mal",

        // New Testament
        BibleBook.MATT to "Matt",
        BibleBook.MARK to "Mark",
        BibleBook.LUKE to "Luke",
        BibleBook.JOHN to "John",
        BibleBook.ACTS to "Acts",
        BibleBook.ROM to "Rom",
        BibleBook.COR1 to "1Cor",
        BibleBook.COR2 to "2Cor",
        BibleBook.GAL to "Gal",
        BibleBook.EPH to "Eph",
        BibleBook.PHIL to "Phil",
        BibleBook.COL to "Col",
        BibleBook.THESS1 to "1Thess",
        BibleBook.THESS2 to "2Thess",
        BibleBook.TIM1 to "1Tim",
        BibleBook.TIM2 to "2Tim",
        BibleBook.TITUS to "Titus",
        BibleBook.PHLM to "Phlm",
        BibleBook.HEB to "Heb",
        BibleBook.JAS to "Jas",
        BibleBook.PET1 to "1Pet",
        BibleBook.PET2 to "2Pet",
        BibleBook.JOHN1 to "1John",
        BibleBook.JOHN2 to "2John",
        BibleBook.JOHN3 to "3John",
        BibleBook.JUDE to "Jude",
        BibleBook.REV to "Rev",

        // Apocrypha
        BibleBook.TOB to "Tob",
        BibleBook.JDT to "Jdt",
        BibleBook.ADD_ESTH to "AddEsth",
        BibleBook.WIS to "Wis",
        BibleBook.SIR to "Sir",
        BibleBook.BAR to "Bar",
        BibleBook.EP_JER to "EpJer",
        BibleBook.PR_AZAR to "PrAzar",
        BibleBook.SUS to "Sus",
        BibleBook.BEL to "Bel",
        BibleBook.MACC1 to "1Macc",
        BibleBook.MACC2 to "2Macc",
        BibleBook.MACC3 to "3Macc",
        BibleBook.MACC4 to "4Macc",
        BibleBook.PR_MAN to "PrMan",
        BibleBook.ESD1 to "1Esd",
        BibleBook.ESD2 to "2Esd",
        BibleBook.PSS151 to "Ps151"
    )

    private val alternateNames = mapOf(
        // Old Testament
        BibleBook.EXOD to "ex",
        BibleBook.RUTH to "rth",
        BibleBook.SAM1 to "isamuel,Samuel,isam,1 sam",
        BibleBook.SAM2 to "iisamuel,iisa,2 sam,Second Samuel",
        BibleBook.KGS1 to "1kg,ikings,ikgs,Kings,iki,ikg,1 kin",
        BibleBook.KGS2 to "2kgs,iikings,iikgs,iiki,iikg,2 kin, Second Kings",
        BibleBook.CHR1 to "ichronicles,1 Chron, 1. Chron,1.Chron,ich,1 chr",
        BibleBook.CHR2 to "iichronicles, 2. Chron, 2 chron, 2.Chron,iich, 2 chr, Second Chronicles",
        BibleBook.PS to "pss,psm,psalm",
        BibleBook.SONG to "ss,songofsongs,sos,canticleofcanticles,canticle,can,coc,sng",
        BibleBook.ISA to "is",
        BibleBook.EZEK to "Ezk",
        BibleBook.JOEL to "Jol",
        BibleBook.JONAH to "jnh",
        BibleBook.NAH to "Nam",

        // New Testament
        BibleBook.MATT to "mt",
        BibleBook.MARK to "mk,mrk",
        BibleBook.LUKE to "lk",
        BibleBook.JOHN to "jn,jhn",
        BibleBook.COR1 to "icorinthians,corinthians,ico",
        BibleBook.COR2 to "iicorinthians,iico, Second Corinthians",
        BibleBook.PHIL to "php",
        BibleBook.COL to "co",
        BibleBook.THESS1 to "ith,thessalonians",
        BibleBook.THESS2 to "iith, Second Thessalonians",
        BibleBook.TIM1 to "1tm,iti,itm,tim,timothy",
        BibleBook.TIM2 to "2tm,iiti,iitm, Second Timothy",
        BibleBook.PHLM to "phm,phlm,philem",
        BibleBook.HEB to "Hebrew",
        BibleBook.JAS to "jas",
        BibleBook.PET1 to "1ptr,ip,1. Pet, 1.Pet, peter",
        BibleBook.PET2 to "2pt,iip,2. Pet, 2.Pet, Second Peter",
        BibleBook.JOHN1 to "1jn,1jh,ijo,ijn,ijh",
        BibleBook.JOHN2 to "2jn,2jh,iijo,iijn,iijh, Second John",
        BibleBook.JOHN3 to "3jn,3jh,iiijo,iiijn,iiijh",
        BibleBook.REV to "rv,apocalypse,revelation",

        // Apocrypha & Other
        BibleBook.SIR to "Ecclesiasticus",
        BibleBook.EP_JER to "letterofjeremiah,letterjeremiah,epistlejeremiah,epjeremiah",
        BibleBook.PR_AZAR to "prayerazariah,prayazariah,songofthreechildren,songthreechildren,songof3children,song3children,S3Y",
        BibleBook.BEL to "beldragon,belanddragon",
        BibleBook.MACC1 to "imaccabees",
        BibleBook.MACC2 to "iimacabees",
        BibleBook.MACC3 to "iiimacabees",
        BibleBook.MACC4 to "ivmac",
        BibleBook.PR_MAN to "prayermanasseh,praymanasseh,prmanasseh",
        BibleBook.ESD1 to "iesdras",
        BibleBook.ESD2 to "iiesdras",
        BibleBook.PSS151 to "pss151,psm151",
        BibleBook.PSALM_SOL to "psssolomon,psmsolomon",
        BibleBook.EP_LAO to "eplaodiceans",
        BibleBook.ESD3 to "iiiesdras",
        BibleBook.ESD4 to "ivesdras",
        BibleBook.ESD5 to "vesdras",
        BibleBook.EN1 to "ienoch",
        BibleBook.CLEM1 to "iclement",
        BibleBook.CLEM2 to "iiclement"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]

    override fun getShortName(book: BibleBook): String? = shortNames[book]

    override fun getAlternateName(book: BibleBook): String? = alternateNames[book]
}
