package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

object FrenchBookNames : BookNameLocalization {
    private val fullNames = mapOf(
        BibleBook.GEN to "Genèse",
        BibleBook.EXOD to "Exode",
        BibleBook.LEV to "Lévitique",
        BibleBook.NUM to "Nombres",
        BibleBook.DEUT to "Deutéronome",
        BibleBook.JOSH to "Josué",
        BibleBook.JUDG to "Juges",
        BibleBook.RUTH to "Ruth",
        BibleBook.SAM1 to "1 Samuel",
        BibleBook.SAM2 to "2 Samuel",
        BibleBook.KGS1 to "1 Rois",
        BibleBook.KGS2 to "2 Rois",
        BibleBook.CHR1 to "1 Chroniques",
        BibleBook.CHR2 to "2 Chroniques",
        BibleBook.EZRA to "Esdras",
        BibleBook.NEH to "Néhémie",
        BibleBook.ESTH to "Esther",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Psaumes",
        BibleBook.PROV to "Proverbes",
        BibleBook.ECCL to "Ecclésiaste",
        BibleBook.SONG to "Cantique des Cantiques",
        BibleBook.ISA to "Ésaïe",
        BibleBook.JER to "Jérémie",
        BibleBook.LAM to "Lamentations",
        BibleBook.EZEK to "Ézéchiel",
        BibleBook.DAN to "Daniel",
        BibleBook.HOS to "Osée",
        BibleBook.JOEL to "Joël",
        BibleBook.AMOS to "Amos",
        BibleBook.OBAD to "Abdias",
        BibleBook.JONAH to "Jonas",
        BibleBook.MIC to "Michée",
        BibleBook.NAH to "Nahum",
        BibleBook.HAB to "Habacuc",
        BibleBook.ZEPH to "Sophonie",
        BibleBook.HAG to "Aggée",
        BibleBook.ZECH to "Zacharie",
        BibleBook.MAL to "Malachie",
        BibleBook.MATT to "Matthieu",
        BibleBook.MARK to "Marc",
        BibleBook.LUKE to "Luc",
        BibleBook.JOHN to "Jean",
        BibleBook.ACTS to "Actes",
        BibleBook.ROM to "Romains",
        BibleBook.COR1 to "1 Corinthiens",
        BibleBook.COR2 to "2 Corinthiens",
        BibleBook.GAL to "Galates",
        BibleBook.EPH to "Éphésiens",
        BibleBook.PHIL to "Philippiens",
        BibleBook.COL to "Colossiens",
        BibleBook.THESS1 to "1 Thessaloniciens",
        BibleBook.THESS2 to "2 Thessaloniciens",
        BibleBook.TIM1 to "1 Timothée",
        BibleBook.TIM2 to "2 Timothée",
        BibleBook.TITUS to "Tite",
        BibleBook.PHLM to "Philémon",
        BibleBook.HEB to "Hébreux",
        BibleBook.JAS to "Jacques",
        BibleBook.PET1 to "1 Pierre",
        BibleBook.PET2 to "2 Pierre",
        BibleBook.JOHN1 to "1 Jean",
        BibleBook.JOHN2 to "2 Jean",
        BibleBook.JOHN3 to "3 Jean",
        BibleBook.JUDE to "Jude",
        BibleBook.REV to "Apocalypse"
    )

    private val shortNames = mapOf(
        BibleBook.GEN to "Gn",
        BibleBook.EXOD to "Ex",
        BibleBook.LEV to "Lv",
        BibleBook.NUM to "Nb",
        BibleBook.DEUT to "Dt",
        BibleBook.JOSH to "Jos",
        BibleBook.JUDG to "Jg",
        BibleBook.RUTH to "Rt",
        BibleBook.SAM1 to "1S",
        BibleBook.SAM2 to "2S",
        BibleBook.KGS1 to "1R",
        BibleBook.KGS2 to "2R",
        BibleBook.CHR1 to "1Ch",
        BibleBook.CHR2 to "2Ch",
        BibleBook.EZRA to "Esd",
        BibleBook.NEH to "Ne",
        BibleBook.ESTH to "Est",
        BibleBook.JOB to "Jb",
        BibleBook.PS to "Ps",
        BibleBook.PROV to "Pr",
        BibleBook.ECCL to "Ec",
        BibleBook.SONG to "Ct",
        BibleBook.ISA to "Es",
        BibleBook.JER to "Jr",
        BibleBook.LAM to "Lm",
        BibleBook.EZEK to "Ez",
        BibleBook.DAN to "Dn",
        BibleBook.HOS to "Os",
        BibleBook.JOEL to "Jl",
        BibleBook.AMOS to "Am",
        BibleBook.OBAD to "Ab",
        BibleBook.JONAH to "Jon",
        BibleBook.MIC to "Mi",
        BibleBook.NAH to "Na",
        BibleBook.HAB to "Ha",
        BibleBook.ZEPH to "So",
        BibleBook.HAG to "Ag",
        BibleBook.ZECH to "Za",
        BibleBook.MAL to "Ml",
        BibleBook.MATT to "Mt",
        BibleBook.MARK to "Mc",
        BibleBook.LUKE to "Lc",
        BibleBook.JOHN to "Jn",
        BibleBook.ACTS to "Ac",
        BibleBook.ROM to "Rm",
        BibleBook.COR1 to "1Co",
        BibleBook.COR2 to "2Co",
        BibleBook.GAL to "Ga",
        BibleBook.EPH to "Ep",
        BibleBook.PHIL to "Ph",
        BibleBook.COL to "Col",
        BibleBook.THESS1 to "1Th",
        BibleBook.THESS2 to "2Th",
        BibleBook.TIM1 to "1Tm",
        BibleBook.TIM2 to "2Tm",
        BibleBook.TITUS to "Tt",
        BibleBook.PHLM to "Phm",
        BibleBook.HEB to "He",
        BibleBook.JAS to "Jc",
        BibleBook.PET1 to "1P",
        BibleBook.PET2 to "2P",
        BibleBook.JOHN1 to "1Jn",
        BibleBook.JOHN2 to "2Jn",
        BibleBook.JOHN3 to "3Jn",
        BibleBook.JUDE to "Jude",
        BibleBook.REV to "Ap"
    )

    private val alternateNames = mapOf(
        BibleBook.DEUT to "Dt,De,Deut",
        BibleBook.SAM1 to "ISamuel",
        BibleBook.SAM2 to "IISamuel",
        BibleBook.KGS1 to "1R,IR,IRo",
        BibleBook.KGS2 to "2R,IIR,IIRo",
        BibleBook.CHR1 to "IChroniques",
        BibleBook.CHR2 to "IIChroniques",
        BibleBook.PS to "Ps,psa",
        BibleBook.SONG to "ss,songofsongs,sos,canticleofcanticles,canticle,can,coc,sng",
        BibleBook.ISA to "Es,Is",
        BibleBook.JOEL to "Joë",
        BibleBook.JONAH to "Jon",
        BibleBook.NAH to "Nah",
        BibleBook.MATT to "Mat",
        BibleBook.MARK to "Mc,Marc",
        BibleBook.LUKE to "Lc,Lu",
        BibleBook.COR1 to "1Co",
        BibleBook.COR2 to "2Co",
        BibleBook.PHIL to "Phil",
        BibleBook.COL to "Col",
        BibleBook.THESS1 to "ITh",
        BibleBook.THESS2 to "2Th",
        BibleBook.TIM1 to "1Ti,1Tm",
        BibleBook.TIM2 to "2Ti,2Tm",
        BibleBook.JAS to "Jc,Ja,Jacq",
        BibleBook.PET1 to "1P",
        BibleBook.PET2 to "2P",
        BibleBook.JOHN1 to "1Jn",
        BibleBook.JOHN2 to "2Jn",
        BibleBook.JOHN3 to "3Jn",
        BibleBook.REV to "Ap,Ré",
        BibleBook.SIR to "Si,Sir",
        BibleBook.EP_JER to "EpJe,LettredeJérémie",
        BibleBook.BEL to "Bel",
        BibleBook.PSALM_SOL to "PsSal",
        BibleBook.EP_LAO to "EpLao"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]
    override fun getShortName(book: BibleBook): String? = shortNames[book]
    override fun getAlternateName(book: BibleBook): String? = alternateNames[book]
}
