package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

object ItalianBookNames : BookNameLocalization {
    private val fullNames = mapOf(
        BibleBook.GEN to "Genesi",
        BibleBook.EXOD to "Esodo",
        BibleBook.LEV to "Levitico",
        BibleBook.NUM to "Numeri",
        BibleBook.DEUT to "Deuteronomio",
        BibleBook.JOSH to "Giosue",
        BibleBook.JUDG to "Giudici",
        BibleBook.RUTH to "Rut",
        BibleBook.SAM1 to "1 Samuele",
        BibleBook.SAM2 to "2 Samuele",
        BibleBook.KGS1 to "1 Re",
        BibleBook.KGS2 to "2 Re",
        BibleBook.CHR1 to "1 Cronache",
        BibleBook.CHR2 to "2 Cronache",
        BibleBook.EZRA to "Esdra",
        BibleBook.NEH to "Neemia",
        BibleBook.ESTH to "Ester",
        BibleBook.JOB to "Giobbe",
        BibleBook.PS to "Salmi",
        BibleBook.PROV to "Proverbi",
        BibleBook.ECCL to "Ecclesiaste",
        BibleBook.SONG to "Cantico dei Cantici",
        BibleBook.ISA to "Isaia",
        BibleBook.JER to "Geremia",
        BibleBook.LAM to "Lamentazioni",
        BibleBook.EZEK to "Ezechiele",
        BibleBook.DAN to "Daniele",
        BibleBook.HOS to "Osea",
        BibleBook.JOEL to "Gioele",
        BibleBook.AMOS to "Amos",
        BibleBook.OBAD to "Abdia",
        BibleBook.JONAH to "Giona",
        BibleBook.MIC to "Michea",
        BibleBook.NAH to "Nahum",
        BibleBook.HAB to "Habacuc",
        BibleBook.ZEPH to "Sofonia",
        BibleBook.HAG to "Aggeo",
        BibleBook.ZECH to "Zaccaria",
        BibleBook.MAL to "Malachia",
        BibleBook.MATT to "Matteo",
        BibleBook.MARK to "Marco",
        BibleBook.LUKE to "Luca",
        BibleBook.JOHN to "Giovanni",
        BibleBook.ACTS to "Atti",
        BibleBook.ROM to "Romani",
        BibleBook.COR1 to "1 Corinzi",
        BibleBook.COR2 to "2 Corinzi",
        BibleBook.GAL to "Galati",
        BibleBook.EPH to "Efesini",
        BibleBook.PHIL to "Filippesi",
        BibleBook.COL to "Colossesi",
        BibleBook.THESS1 to "1 Tessalonicesi",
        BibleBook.THESS2 to "2 Tessalonicesi",
        BibleBook.TIM1 to "1 Timoteo",
        BibleBook.TIM2 to "2 Timoteo",
        BibleBook.TITUS to "Tito",
        BibleBook.PHLM to "Filemone",
        BibleBook.HEB to "Ebrei",
        BibleBook.JAS to "Giacomo",
        BibleBook.PET1 to "1 Pietro",
        BibleBook.PET2 to "2 Pietro",
        BibleBook.JOHN1 to "1 Giovanni",
        BibleBook.JOHN2 to "2 Giovanni",
        BibleBook.JOHN3 to "3 Giovanni",
        BibleBook.JUDE to "Giuda",
        BibleBook.REV to "Apocalisse"
    )

    private val shortNames = mapOf(
        BibleBook.GEN to "Ge",
        BibleBook.EXOD to "Es",
        BibleBook.LEV to "Le",
        BibleBook.NUM to "Nu",
        BibleBook.DEUT to "De",
        BibleBook.JOSH to "Gs",
        BibleBook.JUDG to "Gd",
        BibleBook.RUTH to "Ru",
        BibleBook.SAM1 to "1Sa",
        BibleBook.SAM2 to "2Sa",
        BibleBook.KGS1 to "1Re",
        BibleBook.KGS2 to "2Re",
        BibleBook.CHR1 to "1Cr",
        BibleBook.CHR2 to "2Cr",
        BibleBook.EZRA to "Esd",
        BibleBook.NEH to "Ne",
        BibleBook.ESTH to "Et",
        BibleBook.JOB to "Gb",
        BibleBook.PS to "Sa",
        BibleBook.PROV to "Pr",
        BibleBook.ECCL to "Ec",
        BibleBook.SONG to "Ca",
        BibleBook.ISA to "Is",
        BibleBook.JER to "Gr",
        BibleBook.LAM to "La",
        BibleBook.EZEK to "Ez",
        BibleBook.DAN to "Da",
        BibleBook.HOS to "Os",
        BibleBook.JOEL to "Gl",
        BibleBook.AMOS to "Am",
        BibleBook.OBAD to "Ab",
        BibleBook.JONAH to "Gn",
        BibleBook.MIC to "Mi",
        BibleBook.NAH to "Na",
        BibleBook.HAB to "Ab",
        BibleBook.ZEPH to "So",
        BibleBook.HAG to "Ag",
        BibleBook.ZECH to "Za",
        BibleBook.MAL to "Ml",
        BibleBook.MATT to "Mt",
        BibleBook.MARK to "Mr",
        BibleBook.LUKE to "Lu",
        BibleBook.JOHN to "Gv",
        BibleBook.ACTS to "At",
        BibleBook.ROM to "Ro",
        BibleBook.COR1 to "1Co",
        BibleBook.COR2 to "2Co",
        BibleBook.GAL to "Ga",
        BibleBook.EPH to "Ef",
        BibleBook.PHIL to "Fl",
        BibleBook.COL to "Cl",
        BibleBook.THESS1 to "1Te",
        BibleBook.THESS2 to "2Te",
        BibleBook.TIM1 to "1Ti",
        BibleBook.TIM2 to "2Ti",
        BibleBook.TITUS to "Tt",
        BibleBook.PHLM to "Fm",
        BibleBook.HEB to "Eb",
        BibleBook.JAS to "Gm",
        BibleBook.PET1 to "1Pt",
        BibleBook.PET2 to "2Pt",
        BibleBook.JOHN1 to "1Gv",
        BibleBook.JOHN2 to "2Gv",
        BibleBook.JOHN3 to "3Gv",
        BibleBook.JUDE to "Gd",
        BibleBook.REV to "Ap"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]
    override fun getShortName(book: BibleBook): String? = shortNames[book]
    override fun getAlternateName(book: BibleBook): String? = null
}
