package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

object JapaneseBookNames : BookNameLocalization {
    private val fullNames = mapOf(
        BibleBook.GEN to "創世記",
        BibleBook.EXOD to "出エジプト記",
        BibleBook.LEV to "レビ記",
        BibleBook.NUM to "民数記",
        BibleBook.DEUT to "申命記",
        BibleBook.JOSH to "ヨシュア記",
        BibleBook.JUDG to "士師記",
        BibleBook.RUTH to "ルツ記",
        BibleBook.SAM1 to "サムエル記上",
        BibleBook.SAM2 to "サムエル記下",
        BibleBook.KGS1 to "列王紀上",
        BibleBook.KGS2 to "列王紀下",
        BibleBook.CHR1 to "歴代志上",
        BibleBook.CHR2 to "歴代志下",
        BibleBook.EZRA to "エズラ記",
        BibleBook.NEH to "ネヘミヤ記",
        BibleBook.ESTH to "エステル記",
        BibleBook.JOB to "ヨブ記",
        BibleBook.PS to "詩篇",
        BibleBook.PROV to "箴言",
        BibleBook.ECCL to "伝道の書",
        BibleBook.SONG to "雅歌",
        BibleBook.ISA to "イザヤ書",
        BibleBook.JER to "エレミヤ書",
        BibleBook.LAM to "哀歌",
        BibleBook.EZEK to "エゼキエル書",
        BibleBook.DAN to "ダニエル書",
        BibleBook.HOS to "ホセア書",
        BibleBook.JOEL to "ヨエル書",
        BibleBook.AMOS to "アモス書",
        BibleBook.OBAD to "オバデヤ書",
        BibleBook.JONAH to "ヨナ書",
        BibleBook.MIC to "ミカ書",
        BibleBook.NAH to "ナホム書",
        BibleBook.HAB to "ハバクク書",
        BibleBook.ZEPH to "ゼパニヤ書",
        BibleBook.HAG to "ハガイ書",
        BibleBook.ZECH to "ゼカリヤ書",
        BibleBook.MAL to "マラキ書",
        BibleBook.MATT to "マタイによる福音書",
        BibleBook.MARK to "マルコによる福音書",
        BibleBook.LUKE to "ルカによる福音書",
        BibleBook.JOHN to "ヨハネによる福音書",
        BibleBook.ACTS to "使徒行伝",
        BibleBook.ROM to "ローマ人への手紙",
        BibleBook.COR1 to "コリント人への第一の手紙",
        BibleBook.COR2 to "コリント人への第二の手紙",
        BibleBook.GAL to "ガラテヤ人への手紙",
        BibleBook.EPH to "エペソ人への手紙",
        BibleBook.PHIL to "ピリピ人への手紙",
        BibleBook.COL to "コロサイ人への手紙",
        BibleBook.THESS1 to "テサロニケ人への第一の手紙",
        BibleBook.THESS2 to "テサロニケ人への第二の手紙",
        BibleBook.TIM1 to "テモテへの第一の手紙",
        BibleBook.TIM2 to "テモテへの第一の手紙",
        BibleBook.TITUS to "テトスへの手紙",
        BibleBook.PHLM to "ピレモンへの手紙",
        BibleBook.HEB to "ヘブル人への手紙",
        BibleBook.JAS to "ヤコブの手紙",
        BibleBook.PET1 to "ペテロの第一の手紙",
        BibleBook.PET2 to "ペテロの第二の手紙",
        BibleBook.JOHN1 to "ヨハネの第一の手紙",
        BibleBook.JOHN2 to "ヨハネの第二の手紙",
        BibleBook.JOHN3 to "ヨハネの第三の手紙",
        BibleBook.JUDE to "ユダの手紙",
        BibleBook.REV to "ヨハネの黙示録"
    )

    private val shortNames = mapOf(
        BibleBook.GEN to "創",
        BibleBook.EXOD to "出",
        BibleBook.LEV to "レビ",
        BibleBook.NUM to "民",
        BibleBook.DEUT to "申",
        BibleBook.JOSH to "ヨシ",
        BibleBook.JUDG to "士",
        BibleBook.RUTH to "ルツ",
        BibleBook.SAM1 to "サム上",
        BibleBook.SAM2 to "サム下",
        BibleBook.KGS1 to "王上",
        BibleBook.KGS2 to "王下",
        BibleBook.CHR1 to "代上",
        BibleBook.CHR2 to "代下",
        BibleBook.EZRA to "エズ",
        BibleBook.NEH to "ネヘ",
        BibleBook.ESTH to "エステ",
        BibleBook.JOB to "ヨブ",
        BibleBook.PS to "詩",
        BibleBook.PROV to "箴",
        BibleBook.ECCL to "伝",
        BibleBook.SONG to "雅",
        BibleBook.ISA to "イザ",
        BibleBook.JER to "エレ",
        BibleBook.LAM to "哀",
        BibleBook.EZEK to "エゼ",
        BibleBook.DAN to "ダニ",
        BibleBook.HOS to "ホセ",
        BibleBook.JOEL to "ヨエ",
        BibleBook.AMOS to "アモ",
        BibleBook.OBAD to "オバ",
        BibleBook.JONAH to "ヨナ",
        BibleBook.MIC to "ミカ",
        BibleBook.NAH to "ナホ",
        BibleBook.HAB to "ハバ",
        BibleBook.ZEPH to "ゼパ",
        BibleBook.HAG to "ハガ",
        BibleBook.ZECH to "ゼカ",
        BibleBook.MAL to "マラ",
        BibleBook.MATT to "マタ",
        BibleBook.MARK to "マル",
        BibleBook.LUKE to "ルカ",
        BibleBook.JOHN to "ヨハ",
        BibleBook.ACTS to "行",
        BibleBook.ROM to "ロマ",
        BibleBook.COR1 to "コリ1",
        BibleBook.COR2 to "コリ2",
        BibleBook.GAL to "ガラ",
        BibleBook.EPH to "エペ",
        BibleBook.PHIL to "ピリピ",
        BibleBook.COL to "コロ",
        BibleBook.THESS1 to "テサ1",
        BibleBook.THESS2 to "テサ2",
        BibleBook.TIM1 to "テモ1",
        BibleBook.TIM2 to "テモ2",
        BibleBook.TITUS to "テト",
        BibleBook.PHLM to "ピレ",
        BibleBook.HEB to "ヘブ",
        BibleBook.JAS to "ヤコ",
        BibleBook.PET1 to "ペテ1",
        BibleBook.PET2 to "ペテ2",
        BibleBook.JOHN1 to "ヨハ1",
        BibleBook.JOHN2 to "ヨハ2",
        BibleBook.JOHN3 to "ヨハ3",
        BibleBook.JUDE to "ユダ",
        BibleBook.REV to "默"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]
    override fun getShortName(book: BibleBook): String? = shortNames[book]
    override fun getAlternateName(book: BibleBook): String? = null
}
