package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

object PolishBookNames : BookNameLocalization {
    private val fullNames = mapOf(
        BibleBook.GEN to "Rodzaju",
        BibleBook.EXOD to "Wyjścia",
        BibleBook.LEV to "Kapłańska",
        BibleBook.NUM to "Liczb",
        BibleBook.DEUT to "Powtórzonego Prawa",
        BibleBook.JOSH to "Jozuego",
        BibleBook.JUDG to "Sędziów",
        BibleBook.RUTH to "Rut",
        BibleBook.SAM1 to "1 Samuela",
        BibleBook.SAM2 to "2 Samuela",
        BibleBook.KGS1 to "1 Królewska",
        BibleBook.KGS2 to "2 Królewska",
        BibleBook.CHR1 to "1 Kronik",
        BibleBook.CHR2 to "2 Kronik",
        BibleBook.EZRA to "Ezdrasza",
        BibleBook.NEH to "Nehemiasza",
        BibleBook.ESTH to "Estery",
        BibleBook.JOB to "Hioba",
        BibleBook.PS to "Psalmów",
        BibleBook.PROV to "Przysłów",
        BibleBook.ECCL to "Kaznodziei",
        BibleBook.SONG to "Pieśń nad pieśniami",
        BibleBook.ISA to "Izajasza",
        BibleBook.JER to "Jeremiasza",
        BibleBook.LAM to "Lamentacje",
        BibleBook.EZEK to "Ezechiela",
        BibleBook.DAN to "Daniela",
        BibleBook.HOS to "Ozeasza",
        BibleBook.JOEL to "Joela",
        BibleBook.AMOS to "Amosa",
        BibleBook.OBAD to "Abdiasza",
        BibleBook.JONAH to "Jonasza",
        BibleBook.MIC to "Micheasza",
        BibleBook.NAH to "Nahuma",
        BibleBook.HAB to "Habakuka",
        BibleBook.ZEPH to "Sofoniasza",
        BibleBook.HAG to "Aggeusza",
        BibleBook.ZECH to "Zachariasza",
        BibleBook.MAL to "Malachiasza",
        BibleBook.MATT to "Mateusza",
        BibleBook.MARK to "Marka",
        BibleBook.LUKE to "Łukasza",
        BibleBook.JOHN to "Jana",
        BibleBook.ACTS to "Dzieje",
        BibleBook.ROM to "Rzymian",
        BibleBook.COR1 to "1 Koryntian",
        BibleBook.COR2 to "2 Koryntian",
        BibleBook.GAL to "Galacjan",
        BibleBook.EPH to "Efezjan",
        BibleBook.PHIL to "Filipian",
        BibleBook.COL to "Kolosan",
        BibleBook.THESS1 to "1 Tesaloniczan",
        BibleBook.THESS2 to "2 Tesaloniczan",
        BibleBook.TIM1 to "1 Tymoteusza",
        BibleBook.TIM2 to "2 Tymoteusza",
        BibleBook.TITUS to "Tytusa",
        BibleBook.PHLM to "Filemona",
        BibleBook.HEB to "Hebrajczyków",
        BibleBook.JAS to "Jakuba",
        BibleBook.PET1 to "1 Piotra",
        BibleBook.PET2 to "2 Piotra",
        BibleBook.JOHN1 to "1 Jana",
        BibleBook.JOHN2 to "2 Jana",
        BibleBook.JOHN3 to "3 Jana",
        BibleBook.JUDE to "Judy",
        BibleBook.REV to "Objawienie Jana"
    )

    private val shortNames = mapOf(
        BibleBook.GEN to "Rdz",
        BibleBook.EXOD to "Wj",
        BibleBook.LEV to "Kpł",
        BibleBook.NUM to "Lb",
        BibleBook.DEUT to "Pwt",
        BibleBook.JOSH to "Joz",
        BibleBook.JUDG to "Sdz",
        BibleBook.RUTH to "Rt",
        BibleBook.SAM1 to "1Sm",
        BibleBook.SAM2 to "2Sm",
        BibleBook.KGS1 to "1Krl",
        BibleBook.KGS2 to "2Krl",
        BibleBook.CHR1 to "1Krn",
        BibleBook.CHR2 to "2Krn",
        BibleBook.EZRA to "Ezd",
        BibleBook.NEH to "Ne",
        BibleBook.ESTH to "Est",
        BibleBook.JOB to "Hi",
        BibleBook.PS to "Ps",
        BibleBook.PROV to "Prz",
        BibleBook.ECCL to "Kaz",
        BibleBook.SONG to "Pnp",
        BibleBook.ISA to "Iz",
        BibleBook.JER to "Jr",
        BibleBook.LAM to "Lm",
        BibleBook.EZEK to "Ez",
        BibleBook.DAN to "Dn",
        BibleBook.HOS to "Oz",
        BibleBook.JOEL to "Jl",
        BibleBook.AMOS to "Am",
        BibleBook.OBAD to "Ab",
        BibleBook.JONAH to "Jon",
        BibleBook.MIC to "Mi",
        BibleBook.NAH to "Na",
        BibleBook.HAB to "Ha",
        BibleBook.ZEPH to "So",
        BibleBook.HAG to "Ag",
        BibleBook.ZECH to "Za",
        BibleBook.MAL to "Ml",
        BibleBook.MATT to "Mt",
        BibleBook.MARK to "Mk",
        BibleBook.LUKE to "Łk",
        BibleBook.JOHN to "J",
        BibleBook.ACTS to "Dz",
        BibleBook.ROM to "Rz",
        BibleBook.COR1 to "1Kor",
        BibleBook.COR2 to "2Kor",
        BibleBook.GAL to "Ga",
        BibleBook.EPH to "Ef",
        BibleBook.PHIL to "Flp",
        BibleBook.COL to "Kol",
        BibleBook.THESS1 to "1Tes",
        BibleBook.THESS2 to "2Tes",
        BibleBook.TIM1 to "1Tm",
        BibleBook.TIM2 to "2Tm",
        BibleBook.TITUS to "Tt",
        BibleBook.PHLM to "Flm",
        BibleBook.HEB to "Hbr",
        BibleBook.JAS to "Jk",
        BibleBook.PET1 to "1P",
        BibleBook.PET2 to "2P",
        BibleBook.JOHN1 to "1J",
        BibleBook.JOHN2 to "2J",
        BibleBook.JOHN3 to "3J",
        BibleBook.JUDE to "Jud",
        BibleBook.REV to "Obj"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]
    override fun getShortName(book: BibleBook): String? = shortNames[book]
    override fun getAlternateName(book: BibleBook): String? = null
}
