package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

object RussianBookNames : BookNameLocalization {
    private val fullNames = mapOf(
        BibleBook.GEN to "Бытие",
        BibleBook.EXOD to "Исход",
        BibleBook.LEV to "Левит",
        BibleBook.NUM to "Числа",
        BibleBook.DEUT to "Второзаконие",
        BibleBook.JOSH to "Иисус Навин",
        BibleBook.JUDG to "Судьи",
        BibleBook.RUTH to "Руфь",
        BibleBook.SAM1 to "1. Царств",
        BibleBook.SAM2 to "2. Царств",
        BibleBook.KGS1 to "3. Царств",
        BibleBook.KGS2 to "4. Царств",
        BibleBook.CHR1 to "1. Паралипоменон",
        BibleBook.CHR2 to "2. Паралипоменон",
        BibleBook.EZRA to "Ездра",
        BibleBook.NEH to "Неемия",
        BibleBook.ESTH to "Есфирь",
        BibleBook.JOB to "Иов",
        BibleBook.PS to "Псалтирь",
        BibleBook.PROV to "Притчи",
        BibleBook.ECCL to "Екклесиаст",
        BibleBook.SONG to "Песня Песней",
        BibleBook.ISA to "Исаия",
        BibleBook.JER to "Иеремия",
        BibleBook.LAM to "Плач Иеремии",
        BibleBook.EZEK to "Иезекииль",
        BibleBook.DAN to "Даниил",
        BibleBook.HOS to "Осия",
        BibleBook.JOEL to "Иоиль",
        BibleBook.AMOS to "Амос",
        BibleBook.OBAD to "Авдий",
        BibleBook.JONAH to "Иона",
        BibleBook.MIC to "Михей",
        BibleBook.NAH to "Наум",
        BibleBook.HAB to "Аввакум",
        BibleBook.ZEPH to "Софония",
        BibleBook.HAG to "Аггей",
        BibleBook.ZECH to "Захария",
        BibleBook.MAL to "Малахия",
        BibleBook.MATT to "От Матфея",
        BibleBook.MARK to "От Марка",
        BibleBook.LUKE to "От Луки",
        BibleBook.JOHN to "От Иоанна",
        BibleBook.ACTS to "Деяния",
        BibleBook.ROM to "К Римлянам",
        BibleBook.COR1 to "1. Коринфянам",
        BibleBook.COR2 to "2. Коринфянам",
        BibleBook.GAL to "К Галатам",
        BibleBook.EPH to "К Ефесянам",
        BibleBook.PHIL to "К Филиппийцам",
        BibleBook.COL to "К Колоссянам",
        BibleBook.THESS1 to "1. Фессалоникийцам",
        BibleBook.THESS2 to "2. Фессалоникийцам",
        BibleBook.TIM1 to "1. Тимофею",
        BibleBook.TIM2 to "2. Тимофею",
        BibleBook.TITUS to "К Титу",
        BibleBook.PHLM to "К Филимону",
        BibleBook.HEB to "К Евреям",
        BibleBook.JAS to "Иакова",
        BibleBook.PET1 to "1. Петра",
        BibleBook.PET2 to "2. Петра",
        BibleBook.JOHN1 to "1. Иоанна",
        BibleBook.JOHN2 to "2. Иоанна",
        BibleBook.JOHN3 to "3. Иоанна",
        BibleBook.JUDE to "Иуды",
        BibleBook.REV to "Откровение"
    )

    private val shortNames = mapOf(
        BibleBook.GEN to "Быт",
        BibleBook.EXOD to "Исх",
        BibleBook.LEV to "Лев",
        BibleBook.NUM to "Чис",
        BibleBook.DEUT to "Втор",
        BibleBook.JOSH to "Нав",
        BibleBook.JUDG to "Суд",
        BibleBook.RUTH to "Руф",
        BibleBook.SAM1 to "1Цар",
        BibleBook.SAM2 to "2Цар",
        BibleBook.KGS1 to "3Цар",
        BibleBook.KGS2 to "4Цар",
        BibleBook.CHR1 to "1Пар",
        BibleBook.CHR2 to "2Пар",
        BibleBook.EZRA to "Езд",
        BibleBook.NEH to "Неем",
        BibleBook.ESTH to "Есф",
        BibleBook.JOB to "Иов",
        BibleBook.PS to "Пс",
        BibleBook.PROV to "Прит",
        BibleBook.ECCL to "Еккл",
        BibleBook.SONG to "Песн",
        BibleBook.ISA to "Ис",
        BibleBook.JER to "Иер",
        BibleBook.LAM to "Плач",
        BibleBook.EZEK to "Иез",
        BibleBook.DAN to "Дан",
        BibleBook.HOS to "Ос",
        BibleBook.JOEL to "Иоил",
        BibleBook.AMOS to "Ам",
        BibleBook.OBAD to "Авд",
        BibleBook.JONAH to "Ион",
        BibleBook.MIC to "Мих",
        BibleBook.NAH to "Наум",
        BibleBook.HAB to "Авв",
        BibleBook.ZEPH to "Соф",
        BibleBook.HAG to "Агг",
        BibleBook.ZECH to "Зах",
        BibleBook.MAL to "Мал",
        BibleBook.MATT to "Мф",
        BibleBook.MARK to "Мк",
        BibleBook.LUKE to "Лк",
        BibleBook.JOHN to "Ин",
        BibleBook.ACTS to "Деян",
        BibleBook.ROM to "Рим",
        BibleBook.COR1 to "1Кор",
        BibleBook.COR2 to "2Кор",
        BibleBook.GAL to "Гал",
        BibleBook.EPH to "Еф",
        BibleBook.PHIL to "Фил",
        BibleBook.COL to "Кол",
        BibleBook.THESS1 to "1Фес",
        BibleBook.THESS2 to "2Фес",
        BibleBook.TIM1 to "1Тим",
        BibleBook.TIM2 to "2Тим",
        BibleBook.TITUS to "Тит",
        BibleBook.PHLM to "Флм",
        BibleBook.HEB to "Евр",
        BibleBook.JAS to "Иак",
        BibleBook.PET1 to "1Пет",
        BibleBook.PET2 to "2Пет",
        BibleBook.JOHN1 to "1Ин",
        BibleBook.JOHN2 to "2Ин",
        BibleBook.JOHN3 to "3Ин",
        BibleBook.JUDE to "Иуд",
        BibleBook.REV to "Откр"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]
    override fun getShortName(book: BibleBook): String? = shortNames[book]
    override fun getAlternateName(book: BibleBook): String? = null
}
