/**
 * Distribution License:
 * KSword is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License, version 2.1 or later
 * as published by the Free Software Foundation. This program is distributed
 * in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * The License is available on the internet at:
 * http://www.gnu.org/copyleft/lgpl.html
 * or by writing to:
 * Free Software Foundation, Inc.
 * 59 Temple Place - Suite 330
 * Boston, MA 02111-1307, USA
 *
 * © CrossWire Bible Society, 2005 - 2016
 *
 */
package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

/**
 * Slovenian localized Bible book names.
 * Generated from BibleNames_sl.properties
 */
object SlovenianBookNames : BookNameLocalization {
    private val fullNames = mapOf(
        BibleBook.GEN to "Geneza",
        BibleBook.EXOD to "Eksodus",
        BibleBook.LEV to "Levitik",
        BibleBook.NUM to "Numeri",
        BibleBook.DEUT to "Devteronomij",
        BibleBook.JOSH to "Jozue",
        BibleBook.JUDG to "Sodniki",
        BibleBook.RUTH to "Ruta",
        BibleBook.SAM1 to "1 Samuel",
        BibleBook.SAM2 to "2 Samuel",
        BibleBook.KGS1 to "1 Kraljev",
        BibleBook.KGS2 to "2 Kraljev",
        BibleBook.CHR1 to "1 Kroniška",
        BibleBook.CHR2 to "2 Kroniška",
        BibleBook.EZRA to "Ezra",
        BibleBook.NEH to "Nehemija",
        BibleBook.ESTH to "Estera",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Psalmi",
        BibleBook.PROV to "Pregovori",
        BibleBook.ECCL to "Pridigar",
        BibleBook.SONG to "Pesem pesmi",
        BibleBook.ISA to "Izaija",
        BibleBook.JER to "Jeremija",
        BibleBook.LAM to "Žalostinke",
        BibleBook.EZEK to "Ezekiel",
        BibleBook.DAN to "Daniel",
        BibleBook.HOS to "Ozej",
        BibleBook.JOEL to "Joel",
        BibleBook.AMOS to "Amos",
        BibleBook.OBAD to "Abdija",
        BibleBook.JONAH to "Jona",
        BibleBook.MIC to "Mihej",
        BibleBook.NAH to "Nahum",
        BibleBook.HAB to "Habakuk",
        BibleBook.ZEPH to "Sofonija",
        BibleBook.HAG to "Agej",
        BibleBook.ZECH to "Zaharija",
        BibleBook.MAL to "Malahija",
        BibleBook.MATT to "Matej",
        BibleBook.MARK to "Marko",
        BibleBook.LUKE to "Luka",
        BibleBook.JOHN to "Janez",
        BibleBook.ACTS to "Apostolska dela",
        BibleBook.ROM to "Rimljanom",
        BibleBook.COR1 to "1 Korinčanom",
        BibleBook.COR2 to "2 Korinčanom",
        BibleBook.GAL to "Galačanom",
        BibleBook.EPH to "Efežanom",
        BibleBook.PHIL to "Filipljanom",
        BibleBook.COL to "Kološanom",
        BibleBook.THESS1 to "1 Tesaloničanom",
        BibleBook.THESS2 to "2 Tesaloničanom",
        BibleBook.TIM1 to "1 Timoteju",
        BibleBook.TIM2 to "2 Timoteju",
        BibleBook.TITUS to "Titu",
        BibleBook.PHLM to "Filemonu",
        BibleBook.HEB to "Hebrejcem",
        BibleBook.JAS to "Jakob",
        BibleBook.PET1 to "1  Peter",
        BibleBook.PET2 to "2 Peter",
        BibleBook.JOHN1 to "1 Janez",
        BibleBook.JOHN2 to "2 Janez",
        BibleBook.JOHN3 to "3 Janez",
        BibleBook.JUDE to "Juda",
        BibleBook.REV to "Razodetje"
    )

    private val shortNames = mapOf(
        BibleBook.GEN to "Gen",
        BibleBook.EXOD to "Eks",
        BibleBook.LEV to "Lev",
        BibleBook.NUM to "Num",
        BibleBook.DEUT to "Dev",
        BibleBook.JOSH to "Joz",
        BibleBook.JUDG to "Sod",
        BibleBook.RUTH to "Rut",
        BibleBook.SAM1 to "1 Sam",
        BibleBook.SAM2 to "2 Sam",
        BibleBook.KGS1 to "1 Kr",
        BibleBook.KGS2 to "2 Kr",
        BibleBook.CHR1 to "1 Krn",
        BibleBook.CHR2 to "2 Krn",
        BibleBook.EZRA to "Ezr",
        BibleBook.NEH to "Neh",
        BibleBook.ESTH to "Est",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Ps",
        BibleBook.PROV to "Prg",
        BibleBook.ECCL to "Prd",
        BibleBook.SONG to "Pp",
        BibleBook.ISA to "Iz",
        BibleBook.JER to "Jer",
        BibleBook.LAM to "Žal",
        BibleBook.EZEK to "Ezk",
        BibleBook.DAN to "Dan",
        BibleBook.HOS to "Oz",
        BibleBook.JOEL to "Jl",
        BibleBook.AMOS to "Am",
        BibleBook.OBAD to "Abd",
        BibleBook.JONAH to "Jon",
        BibleBook.MIC to "Mih",
        BibleBook.NAH to "Nah",
        BibleBook.HAB to "Hab",
        BibleBook.ZEPH to "Sof",
        BibleBook.HAG to "Ag",
        BibleBook.ZECH to "Zah",
        BibleBook.MAL to "Mal",
        BibleBook.MATT to "Mt",
        BibleBook.MARK to "Mr",
        BibleBook.LUKE to "Lk",
        BibleBook.JOHN to "Jn",
        BibleBook.ACTS to "Apd",
        BibleBook.ROM to "Rim",
        BibleBook.COR1 to "1 Kor",
        BibleBook.COR2 to "2 Kor",
        BibleBook.GAL to "Gal",
        BibleBook.EPH to "Ef",
        BibleBook.PHIL to "Flp",
        BibleBook.COL to "Kol",
        BibleBook.THESS1 to "1 Tes",
        BibleBook.THESS2 to "2 Tes",
        BibleBook.TIM1 to "1 Tim",
        BibleBook.TIM2 to "2 Tim",
        BibleBook.TITUS to "Tit",
        BibleBook.PHLM to "Flm",
        BibleBook.HEB to "Heb",
        BibleBook.JAS to "Jak",
        BibleBook.PET1 to "1 Pt",
        BibleBook.PET2 to "2 Pt",
        BibleBook.JOHN1 to "1 Jn",
        BibleBook.JOHN2 to "2 Jn",
        BibleBook.JOHN3 to "3 Jn",
        BibleBook.JUDE to "Jud",
        BibleBook.REV to "Raz"
    )

    private val alternateNames = mapOf(
        BibleBook.GEN to "1Mz,1. Mz,1 Mz",
        BibleBook.EXOD to "2Mz,2. Mz,2 Mz",
        BibleBook.LEV to "3Mz,3. Mz,3 Mz",
        BibleBook.NUM to "4Mz,4. Mz,4 Mz",
        BibleBook.DEUT to "5Mz,5. Mz,5 Mz",
        BibleBook.JOSH to "Josh",
        BibleBook.JUDG to "Judg",
        BibleBook.RUTH to "Ruth",
        BibleBook.SAM1 to "1. Samuel,1. Sam,1 Sam,1Sam",
        BibleBook.SAM2 to "2. Samuel,2. Sam,2 Sam,2Sam",
        BibleBook.KGS1 to "1. Kraljev,1. Kr,1 Kr,1Kgs",
        BibleBook.KGS2 to "2. Kraljev,2. Kr,2 Kr,2Kgs",
        BibleBook.CHR1 to "1 Kroniska,1 Kroniška,1. Kroniska,1. Kroniška,1. Krn,1 Krn",
        BibleBook.CHR2 to "2 Kroniska,2 Kroniška,2. Kroniska,2. Kroniška,2. Krn,2 Krn",
        BibleBook.SONG to "ss,songofsongs,sos,canticleofcanticles,canticle,can,coc,sng,pp,sng,Vp,Visoka pesem,V p",
        BibleBook.ISA to "Iza",
        BibleBook.LAM to "Lam",
        BibleBook.EZEK to "Ezk,Ezek",
        BibleBook.DAN to "Daniel,Danijel,Dan",
        BibleBook.OBAD to "Obad,Obd,Abd",
        BibleBook.JONAH to "Jon,Jn",
        BibleBook.MIC to "Mic,Mh",
        BibleBook.NAH to "Nam,Nah,Nh",
        BibleBook.ZECH to "Zah,Zeh",
        BibleBook.MAL to "Ml",
        BibleBook.MATT to "Matt",
        BibleBook.MARK to "Mark",
        BibleBook.LUKE to "Luke",
        BibleBook.JOHN to "John",
        BibleBook.ROM to "Rom",
        BibleBook.COR1 to "1. Korinčanom,1 Korinčanom,1. Korincanom,1 Korincanom,1. Kor,1Kor",
        BibleBook.COR2 to "2. Korinčanom,2 Korinčanom,2. Korincanom,2 Korincanom,2. Kor,2Kor",
        BibleBook.EPH to "Efe",
        BibleBook.PHIL to "Flp,Filip",
        BibleBook.COL to "Col",
        BibleBook.THESS1 to "1. Tesaloničanom,1 Tesaloničanom,1. Tesalonicanom,1 Tesalonicanom,1. Tes,1Tes",
        BibleBook.THESS2 to "2. Tesaloničanom,2 Tesaloničanom,2. Tesalonicanom,2Tesalonicanom,2. Tes,2Tes",
        BibleBook.TIM1 to "1. Tim,1 Tim,1Tim,1 Timoteju,1Timoteju,1Timotej,1. Timotej,1 Timotej",
        BibleBook.TIM2 to "2. Tim,2 Tim,2Tim,2 Timoteju,2Timoteju,2Timotej,2. Timotej,2 Timotej",
        BibleBook.TITUS to "Titus",
        BibleBook.PHLM to "Flm,Filemon",
        BibleBook.HEB to "Hebr",
        BibleBook.JAS to "Jak",
        BibleBook.PET1 to "1Peter,1. Peter,1 Peter,1Petrovo,1. Petrovo,1 Petrovo,1. Pt,1 Pt,1 Pet,1.Pet",
        BibleBook.PET2 to "2Peter,2. Peter,2 Peter,2Petrovo,2. Petrovo,2 Petrovo,2. Pt,2 Pt,2 Pet,2.Pet",
        BibleBook.JOHN1 to "1Janez,1. Janez,1 Janez,1Janezovo,1. Janezovo,1 Janezovo,1. Jn,1 Jn,1 Jan,1. Jan",
        BibleBook.JOHN2 to "2Janez,2. Janez,2 Janez,2Janezovo,2. Janezovo,2 Janezovo,2. Jn,2 Jn,2 Jan,2. Jan",
        BibleBook.JOHN3 to "Janez,3. Janez,3 Janez,3Janezovo,3. Janezovo,3 Janezovo,3. Jn,3 Jn,3 Jan,3. Jan",
        BibleBook.JUDE to "Jude,Jd,Jud",
        BibleBook.REV to "Rev",
        BibleBook.MACC1 to "1. Mkb,1 Mkb,1. Mak,1 Mak,1. Makabejci,1 Makabejci,1Makabejci",
        BibleBook.MACC2 to "2. Mkb,2 Mkb,2. Mak,2 Mak,2. Makabejci,2 Makabejci,2Makabejci",
        BibleBook.MACC3 to "3. Mkb,3 Mkb,3. Mak,3 Mak,3. Makabejci,3 Makabejci,3Makabejci",
        BibleBook.MACC4 to "4. Mkb,4 Mkb,4. Mak,4 Mak,4. Makabejci,4 Makabejci,4Makabejci",
        BibleBook.ESD1 to "1. Ez,1 Ez,1. Ezd,1Ezd,1 Ezd",
        BibleBook.ESD2 to "2. Ez,2 Ez,2. Ezd,2Ezd,2 Ezd",
        BibleBook.PSS151 to "Ps151,Psalm 151",
        BibleBook.PSALM_SOL to "Ps Sol",
        BibleBook.EN1 to "1. En,1En,Henoh,Henohova knjiga",
        BibleBook.ESD3 to "3. Ez,3 Ez,3. Ezd,3Ezd,3 Ezd",
        BibleBook.ESD4 to "4. Ez,4 Ez,4. Ezd,4Ezd,4 Ezd",
        BibleBook.ESD5 to "5. Ez,5 Ez,5. Ezd,5Ezd,5 Ezd",
        BibleBook.CLEM1 to "1Klem",
        BibleBook.CLEM2 to "2Klem"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]
    override fun getShortName(book: BibleBook): String? = shortNames[book]
    override fun getAlternateName(book: BibleBook): String? = alternateNames[book]
}
