package org.crosswire.ksword.versification.localization

import org.crosswire.ksword.versification.BibleBook

/**
 * Spanish localization for Bible book names
 */
object SpanishBookNames : BookNameLocalization {

    private val fullNames = mapOf(
        // Introductions
        BibleBook.INTRO_BIBLE to "Introducción a la Biblia",
        BibleBook.INTRO_OT to "Introducción al Antiguo Testamento",
        BibleBook.INTRO_NT to "Introducción al Nuevo Testamento",

        // Old Testament
        BibleBook.GEN to "Génesis",
        BibleBook.EXOD to "Éxodo",
        BibleBook.LEV to "Levítico",
        BibleBook.NUM to "Números",
        BibleBook.DEUT to "Deuteronomio",
        BibleBook.JOSH to "Josué",
        BibleBook.JUDG to "Jueces",
        BibleBook.RUTH to "Rut",
        BibleBook.SAM1 to "1 Samuel",
        BibleBook.SAM2 to "2 Samuel",
        BibleBook.KGS1 to "1 Reyes",
        BibleBook.KGS2 to "2 Reyes",
        BibleBook.CHR1 to "1 Crónicas",
        BibleBook.CHR2 to "2 Crónicas",
        BibleBook.EZRA to "Esdras",
        BibleBook.NEH to "Nehemías",
        BibleBook.ESTH to "Ester",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Salmos",
        BibleBook.PROV to "Proverbios",
        BibleBook.ECCL to "Eclesiastés",
        BibleBook.SONG to "Cantares",
        BibleBook.ISA to "Isaías",
        BibleBook.JER to "Jeremías",
        BibleBook.LAM to "Lamentaciones",
        BibleBook.EZEK to "Ezequiel",
        BibleBook.DAN to "Daniel",
        BibleBook.HOS to "Oseas",
        BibleBook.JOEL to "Joel",
        BibleBook.AMOS to "Amós",
        BibleBook.OBAD to "Abdías",
        BibleBook.JONAH to "Jonás",
        BibleBook.MIC to "Miqueas",
        BibleBook.NAH to "Nahúm",
        BibleBook.HAB to "Habacuc",
        BibleBook.ZEPH to "Sofonías",
        BibleBook.HAG to "Hageo",
        BibleBook.ZECH to "Zacarías",
        BibleBook.MAL to "Malaquías",

        // New Testament
        BibleBook.MATT to "Mateo",
        BibleBook.MARK to "Marcos",
        BibleBook.LUKE to "Lucas",
        BibleBook.JOHN to "Juan",
        BibleBook.ACTS to "Hechos",
        BibleBook.ROM to "Romanos",
        BibleBook.COR1 to "1 Corintios",
        BibleBook.COR2 to "2 Corintios",
        BibleBook.GAL to "Gálatas",
        BibleBook.EPH to "Efesios",
        BibleBook.PHIL to "Filipenses",
        BibleBook.COL to "Colosenses",
        BibleBook.THESS1 to "1 Tesalonicenses",
        BibleBook.THESS2 to "2 Tesalonicenses",
        BibleBook.TIM1 to "1 Timoteo",
        BibleBook.TIM2 to "2 Timoteo",
        BibleBook.TITUS to "Tito",
        BibleBook.PHLM to "Filemón",
        BibleBook.HEB to "Hebreos",
        BibleBook.JAS to "Santiago",
        BibleBook.PET1 to "1 Pedro",
        BibleBook.PET2 to "2 Pedro",
        BibleBook.JOHN1 to "1 Juan",
        BibleBook.JOHN2 to "2 Juan",
        BibleBook.JOHN3 to "3 Juan",
        BibleBook.JUDE to "Judas",
        BibleBook.REV to "Apocalipsis",

        // Apocrypha
        BibleBook.TOB to "Tobías",
        BibleBook.JDT to "Judit",
        BibleBook.ADD_ESTH to "Adiciones a Ester",
        BibleBook.WIS to "Sabiduría",
        BibleBook.SIR to "Eclesiástico",
        BibleBook.BAR to "Baruc",
        BibleBook.EP_JER to "Carta de Jeremías",
        BibleBook.PR_AZAR to "Oración de Azarías",
        BibleBook.SUS to "Susana",
        BibleBook.BEL to "Bel y el Dragón",
        BibleBook.MACC1 to "1 Macabeos",
        BibleBook.MACC2 to "2 Macabeos",
        BibleBook.MACC3 to "3 Macabeos",
        BibleBook.MACC4 to "4 Macabeos",
        BibleBook.PR_MAN to "Oración de Manasés",
        BibleBook.ESD1 to "1 Esdras",
        BibleBook.ESD2 to "2 Esdras",
        BibleBook.PSS151 to "Salmo 151"
    )

    private val shortNames = mapOf(
        // Introductions
        BibleBook.INTRO_BIBLE to "Intro",
        BibleBook.INTRO_OT to "Intro AT",
        BibleBook.INTRO_NT to "Intro NT",

        // Old Testament
        BibleBook.GEN to "Gén",
        BibleBook.EXOD to "Éxo",
        BibleBook.LEV to "Lev",
        BibleBook.NUM to "Núm",
        BibleBook.DEUT to "Deut",
        BibleBook.JOSH to "Jos",
        BibleBook.JUDG to "Jue",
        BibleBook.RUTH to "Rut",
        BibleBook.SAM1 to "1Sam",
        BibleBook.SAM2 to "2Sam",
        BibleBook.KGS1 to "1Rey",
        BibleBook.KGS2 to "2Rey",
        BibleBook.CHR1 to "1Crón",
        BibleBook.CHR2 to "2Crón",
        BibleBook.EZRA to "Esd",
        BibleBook.NEH to "Neh",
        BibleBook.ESTH to "Est",
        BibleBook.JOB to "Job",
        BibleBook.PS to "Sal",
        BibleBook.PROV to "Prov",
        BibleBook.ECCL to "Ecl",
        BibleBook.SONG to "Cant",
        BibleBook.ISA to "Isa",
        BibleBook.JER to "Jer",
        BibleBook.LAM to "Lam",
        BibleBook.EZEK to "Eze",
        BibleBook.DAN to "Dan",
        BibleBook.HOS to "Os",
        BibleBook.JOEL to "Joel",
        BibleBook.AMOS to "Amós",
        BibleBook.OBAD to "Abd",
        BibleBook.JONAH to "Jon",
        BibleBook.MIC to "Miq",
        BibleBook.NAH to "Nah",
        BibleBook.HAB to "Hab",
        BibleBook.ZEPH to "Sof",
        BibleBook.HAG to "Hag",
        BibleBook.ZECH to "Zac",
        BibleBook.MAL to "Mal",

        // New Testament
        BibleBook.MATT to "Mat",
        BibleBook.MARK to "Mar",
        BibleBook.LUKE to "Luc",
        BibleBook.JOHN to "Juan",
        BibleBook.ACTS to "Hech",
        BibleBook.ROM to "Rom",
        BibleBook.COR1 to "1Cor",
        BibleBook.COR2 to "2Cor",
        BibleBook.GAL to "Gál",
        BibleBook.EPH to "Efe",
        BibleBook.PHIL to "Fil",
        BibleBook.COL to "Col",
        BibleBook.THESS1 to "1Tes",
        BibleBook.THESS2 to "2Tes",
        BibleBook.TIM1 to "1Tim",
        BibleBook.TIM2 to "2Tim",
        BibleBook.TITUS to "Tito",
        BibleBook.PHLM to "Filem",
        BibleBook.HEB to "Heb",
        BibleBook.JAS to "Sant",
        BibleBook.PET1 to "1Ped",
        BibleBook.PET2 to "2Ped",
        BibleBook.JOHN1 to "1Juan",
        BibleBook.JOHN2 to "2Juan",
        BibleBook.JOHN3 to "3Juan",
        BibleBook.JUDE to "Judas",
        BibleBook.REV to "Apoc",

        // Apocrypha
        BibleBook.TOB to "Tob",
        BibleBook.JDT to "Jdt",
        BibleBook.ADD_ESTH to "AdiEst",
        BibleBook.WIS to "Sab",
        BibleBook.SIR to "Eclo",
        BibleBook.BAR to "Bar",
        BibleBook.EP_JER to "CartJer",
        BibleBook.PR_AZAR to "OrAz",
        BibleBook.SUS to "Sus",
        BibleBook.BEL to "Bel",
        BibleBook.MACC1 to "1Mac",
        BibleBook.MACC2 to "2Mac",
        BibleBook.MACC3 to "3Mac",
        BibleBook.MACC4 to "4Mac",
        BibleBook.PR_MAN to "OrMan",
        BibleBook.ESD1 to "1Esd",
        BibleBook.ESD2 to "2Esd",
        BibleBook.PSS151 to "Sal151"
    )

    override fun getFullName(book: BibleBook): String? = fullNames[book]

    override fun getShortName(book: BibleBook): String? = shortNames[book]

    override fun getAlternateName(book: BibleBook): String? = null
}
